packages:
    - packages/*
linkWorkspacePackages: true
includeWorkspaceRoot: true
catalog:
    '@eslint/eslintrc': ^3
    '@mantine/carousel': ^7.17.1
    '@mantine/charts': ^7.17.1
    '@mantine/code-highlight': ^7.17.1
    '@mantine/core': ^7.17.1
    '@mantine/dates': ^7.17.1
    '@mantine/dropzone': ^7.17.1
    '@mantine/form': ^7.17.1
    '@mantine/hooks': ^7.17.1
    '@mantine/modals': ^7.17.1
    '@mantine/notifications': ^7.17.1
    '@mantine/nprogress': ^7.17.1
    '@mantine/spotlight': ^7.17.1
    '@mantine/tiptap': ^7.17.1
    '@tailwindcss/postcss': ^4
    '@tiptap/extension-link': ^2.11.5
    '@tiptap/pm': ^2.11.5
    '@tiptap/react': ^2.11.5
    '@tiptap/starter-kit': ^2.11.5
    '@types/node': ^20
    '@types/react': ^19
    '@types/react-dom': ^19
    dayjs: ^1.11.13
    embla-carousel-react: ^7.1.0
    eslint: ^9
    eslint-config-next: 15.2.1
    lodash-es: ^4.17.21
    next: 15.2.1
    postcss: ^8.5.3
    postcss-preset-mantine: ^1.17.0
    postcss-simple-vars: ^7.0.1
    react: ^19.0.0
    react-dom: ^19.0.0
    recharts: '2'
    tailwindcss: ^4
    typescript: ^5
